const data={
'1':['How to Add Echo to Only Part of a Song','Select the exact timeline range first. Then apply delay, feedback and wet/dry mix only to that region. This keeps verses, intros and other sections untouched. A short delay with moderate feedback creates a controlled echo; longer times create a more obvious repeat. Always preview because feedback can build energy quickly.'],
'2':['MP3 320 kbps Explained','320 kbps is a high MP3 bitrate that preserves more encoded audio information than lower bitrates, but it cannot restore detail that was missing from the source. Exporting a low-quality file at 320 kbps does not magically upgrade the original. Use it when you want a high-bitrate MP3 deliverable and can accept the larger file size.'],
'3':['Why Audio Plays in Only One Ear','One-ear playback commonly happens when mono audio is written only to the left or right channel, or when channel mapping is handled incorrectly during export. A safer export path creates a two-channel render and, when the source is mono, duplicates that source into both output channels.'],
'4':['How to Cut Audio at an Exact Timestamp','Use a waveform plus numeric timestamps. Mark a start and end time, preview the removal, and keep the edit non-destructive until export. Exact cuts are easier to revise than destructive source-file edits.'],
'5':['Bass Boost Without Clipping','Bass boost adds energy to low frequencies and can push peaks beyond digital full scale. Use a low-shelf filter, keep boost moderate, reduce gain if needed, and normalize only when peaks exceed safe limits. More bass is not automatically better; speakers and headphones remain stubbornly physical objects.'],
'6':['Browser Audio Editing vs Desktop DAWs','Browser editors are convenient for focused tasks such as trimming, region effects, quick previews and MP3 export. Desktop DAWs remain stronger for large multitrack sessions, advanced plugins, automation lanes and professional mastering workflows.']
};
export async function generateMetadata({params}){const {id}=await params;return {title:data[id]?.[0]||'Audio Guide'}}
export default async function Post({params}){const {id}=await params;const p=data[id]||['Audio Guide','Guide unavailable.'];return <main className="page prose"><div className="eyebrow">AUDIO EDITING GUIDE</div><h1 className="pageTitle">{p[0]}</h1><p>{p[1]}</p><h2>Practical workflow</h2><p>Work from the cleanest source available, make small changes, preview on headphones and speakers, and keep your original file untouched until you are satisfied with the export.</p></main>}
